### Suma de matrices aleatorias

In [4]:
import numpy as np, random

def suma_matrices_rand():
    print("*** Dimensiones de la primera matriz ***")
    n = int(input("Ingrese el número de filas de la matriz: "))
    m = int(input("Ingrese el número de columnas de la matriz: "))

    print("\n*** Dimensiones de la segunda matriz ***")
    r = int(input("Ingrese el número de filas de la matriz: "))
    s = int(input("Ingrese el número de columnas de la matriz: "))
    
    # se crean las matrices con números aleatorios enteros 0-100
    a = np.random.randint(0, 100, size=(n, m))
    b = np.random.randint(0, 100, size=(r, s))
    
    if(n!=r | m!=s):
            print("\nLas dimensiones de las matrices son diferentes")
            print("No se puede realizar la operación")
    else:
        #crea una matriz de ceros nxm (dtype=int --> para numeros enteros)
        c = np.zeros((n,m), dtype=int)
        for i in range(n):
            for j in range(m):
                #realiza la suma de a con b
                c[i][j] = (a[i][j] + b[i][j])

        print("A = \n", a, "\n")
        print("B = \n", b, "\n")
        print("\n A + B = \n",c)

In [129]:
suma_matrices_rand()

*** Dimensiones de la primera matriz ***
Ingrese el número de filas de la matriz: 2
Ingrese el número de columnas de la matriz: 2

*** Dimensiones de la segunda matriz ***
Ingrese el número de filas de la matriz: 2
Ingrese el número de columnas de la matriz: 2
A = 
 [[18 75]
 [50 67]] 

B = 
 [[41 52]
 [74 27]] 


 A + B = 
 [[ 59 127]
 [124  94]]


### Suma de matrices

In [91]:
import numpy as np

def suma_matrices():
    a = []
    b = []
    
    # Definición del tamaño de la matriz A
    print("*** Dimensiones de la primera matriz ***")
    n = int(input("Ingrese el número de filas de la matriz: "))
    m = int(input("Ingrese el número de columnas de la matriz: "))
    
    # Definición del tamaño de la matriz B
    print("\n*** Dimensiones de la segunda matriz ***")
    r = int(input("Ingrese el número de filas de la matriz: "))
    s = int(input("Ingrese el número de columnas de la matriz: "))
    
    # Se verifican las dimensiones de ambas matrices
    if(n!=r | m!=s):
        print("\nLas dimensiones de las matrices son diferentes")
        print("No se puede realizar la operación")
    else:
        # Llenado de matriz A
        print("\n* Llenado de matriz A *")
        for i in range(n):
            a.append([0]*m)
            for j in range(m):
                a[i][j] = int(input("\nIngrese el valor (%d,%d): " % (i, j)))
    
        # Llenado de matriz B
        print("\n* Llenado de matriz B *")
        for i in range(r):
            b.append([0]*s)
            for j in range(s):
                b[i][j] = int(input("\nIngrese el valor (%d,%d): " % (i, j)))
        
        #crea una matriz C de ceros nxm
        c = np.zeros((n,m), dtype=int)
        
        for i in range(n):
            for j in range(m):
                #realiza la suma de a con b
                c[i][j] = (a[i][j] + b[i][j])

        print("A = \n", np.array(a), "\n")
        print("B = \n", np.array(b), "\n")
        print("\n A + B = \n", np.array(c))

In [93]:
suma_matrices()

*** Dimensiones de la primera matriz ***
Ingrese el número de filas de la matriz: 2
Ingrese el número de columnas de la matriz: 3

*** Dimensiones de la segunda matriz ***
Ingrese el número de filas de la matriz: 4
Ingrese el número de columnas de la matriz: 2

Las dimensiones de las matrices son diferentes
No se puede realizar la operación


In [94]:
suma_matrices()

*** Dimensiones de la primera matriz ***
Ingrese el número de filas de la matriz: 3
Ingrese el número de columnas de la matriz: 3

*** Dimensiones de la segunda matriz ***
Ingrese el número de filas de la matriz: 3
Ingrese el número de columnas de la matriz: 3

* Llenado de matriz A *

Ingrese el valor (0,0): 1

Ingrese el valor (0,1): 2

Ingrese el valor (0,2): 3

Ingrese el valor (1,0): 4

Ingrese el valor (1,1): 5

Ingrese el valor (1,2): 6

Ingrese el valor (2,0): 7

Ingrese el valor (2,1): 8

Ingrese el valor (2,2): 9

* Llenado de matriz B *

Ingrese el valor (0,0): 1

Ingrese el valor (0,1): 2

Ingrese el valor (0,2): 3

Ingrese el valor (1,0): 4

Ingrese el valor (1,1): 5

Ingrese el valor (1,2): 6

Ingrese el valor (2,0): 7

Ingrese el valor (2,1): 8

Ingrese el valor (2,2): 9
A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

B = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 


 A + B = 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
