In [128]:
import numpy as np, random

def suma_matrices():
    print("*** Dimensiones de la primera matriz ***")
    n = int(input("Ingrese el número de filas de la matriz: "))
    m = int(input("Ingrese el número de columnas de la matriz: "))

    print("\n*** Dimensiones de la segunda matriz ***")
    r = int(input("Ingrese el número de filas de la matriz: "))
    s = int(input("Ingrese el número de columnas de la matriz: "))
    
    # se crean las matrices con números aleatorios enteros 0-100
    a = np.random.randint(0, 100, size=(n, m))
    b = np.random.randint(0, 100, size=(r, s))
    
    if(n!=r | m!=s):
        print("\nLas dimensiones de las matrices son diferentes")
        print("No se puede realizar la operación")
    else:
        #crea una matriz de ceros nxm (dtype=int --> para numeros enteros)
        c = np.zeros((n,m), dtype=int)
        for i in range(n):
            for j in range(m):
                #realiza la suma de a con b
                c[i][j] = (a[i][j] + b[i][j])
    
    print("A = \n", a, "\n")
    print("B = \n", b, "\n")
    print("\n A + B = \n",c)


In [129]:
suma_matrices()

*** Dimensiones de la primera matriz ***
Ingrese el número de filas de la matriz: 2
Ingrese el número de columnas de la matriz: 2

*** Dimensiones de la segunda matriz ***
Ingrese el número de filas de la matriz: 2
Ingrese el número de columnas de la matriz: 2
A = 
 [[18 75]
 [50 67]] 

B = 
 [[41 52]
 [74 27]] 


 A + B = 
 [[ 59 127]
 [124  94]]
